bug:
- all:
    - base-branch: ['main-*']
    - head-branch: ['*/bug/*']

enhancement:
- all:
    - base-branch: ['main-*']
    - head-branch: ['*/enhancement/*']

documentation:
- any:
    - changed-files: ['README.md']
