bug:
- all:
    - base-branch: ['main-*']
    - head-branch: ['^[\D\d]+\/bug\/[\D\d]+']

enhancement:
- all:
    - base-branch: ['main-*']
    - head-branch: ['^[\D\d]+\/enhancement\/[\D\d]+']

documentation:
- any:
    - changed-files: ['README.md']

workflow:
- any:
    - changed-files: ['.github/**']
