name: Dummy action

on:
  pull_request_target:
    branches: ["main-dev"]

jobs:
  dummt_tests:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Dummy logs..."
    - run: echo "${{ secrets.SUPER_SECRET }}"
    - run: echo "Broken workfows?.."
