name: "Auto labeling"
on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'main-**'

jobs:
  triage:
    name: "Checking for labels"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "TrixiEther/4Tests"
      - id: label-the-PR
        uses: actions/labeler@v5.0.0-alpha.1
        with:
          repo-token: "${{ secrets.TEST_TOKEN }}"
          sync-labels: true
          dot: true
          configuration-path: ".github/labeler.config.yml"
      - id: post-labeling-process
        if: contains(steps.label-the-PR.outputs.all-labels, 'workflow')
        run: |
          echo "Workflow tag found"
