name: "Auto labeling"
on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'main-**'

jobs:
  triage:
    name: "Checking for labels"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.TEST_TOKEN }}"
          sync-labels: true
          configuration-path: ".github/labeler.config.yml"