name: Python runner - test

on:
  push:
    branches:
      - main-dev

jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
    - name: Install aapt
      run: sudo apt-get -y install aapt
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install requests
    - name: Checkout Dashchan-Meta
      uses: actions/checkout@v3
      with: 
        repository: ${{ secrets.META_DASHCHAN_REPO }}
        path: meta/
    - run: ls -l
    - working-directory: meta
      run: |
        git checkout master
        git status
    - run: python meta/generate.py
    - run: |
        mkdir test1
        mkdir test2
        echo "Hello" > test1/1.file
        echo "Holla" > test1/2.file
        ls test1 | xargs -I something cp test1/something test2/something
        ls test2


    
