name: Python runner - test

on:
  push:
    branches:
      - main-dev

jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
    - name: Install aapt
      run: sudo apt-get -y install aapt
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install requests
    - name: Checkout Dashchan-Meta
      uses: actions/checkout@v3
      with: 
        repository: ${{ secrets.META_DASHCHAN_REPO }}
        path: meta/
    - run: python meta/generate.py


    
