name: Python runner - test

on:
  push:
    branches:
      - master

jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Checkout Dashchan-Meta
      uses: actions/checkout@v3
      with: 
        repository: ${{ secrets.META_DASHCHAN_REPO }}
        path: meta/
    - run: python meta/generate.py


    
